### ISSUE TITLE
error running app

### ISSUE THREAD

**Issue by Data-drone** [streamlit/demo-self-driving#10]
I tried to use this app in a docker container and when I select the "run the app" app mode it doesn't work.

I get:

```
UnhashableType: Cannot hash object of type numpy.ufunc

While caching some code, Streamlit encountered an object of type numpy.ufunc. You’ll need to help Streamlit understand how to hash that type with the hash_funcs argument. For example:


@st.cache(hash_funcs={numpy.ufunc: my_hash_func})
def my_func(...):
    ...
Please see the hash_funcs documentation for more details.

Traceback:
  File "/tmp/tmprl6zpn8j/app.py", line 296, in <module>
    main()
  File "/tmp/tmprl6zpn8j/app.py", line 45, in main
    run_the_app()
  File "/tmp/tmprl6zpn8j/app.py", line 116, in run_the_app
    selected_frame_index, selected_frame = frame_selector_ui(summary)
  File "/tmp/tmprl6zpn8j/app.py", line 147, in frame_selector_ui
    selected_frames = get_selected_frames(summary, object_type, min_elts, max_elts)
```

I am using docker container `python:latest` and running:
`pip install --upgrade streamlit opencv-python` as specified in the readme.

Python is: `Python 3.8.1`

pip is installing numpy: `numpy-1.18.1`

any ideas?

**Comment by monchier** [comment]
Thanks for the report!!!
We are tracking this on the Streamlit side: https://github.com/streamlit/streamlit/issues/1057

**Comment by tc87** [comment]
Closing this since a fix was merged [Custom hashing logic for numpy.ufunc types #1066](https://github.com/streamlit/streamlit/pull/1066).
