### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by EteimZ** [streamlit/demo-self-driving#20]
# Short Story

This app doesn't work on streamlit sharing

# Long Story

I am working on an object detection app with streamlit it works perfectly on my system but when i try to deploy it on Streamlit Sharing I get this error:

```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Traceback:
File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "/app/demo-self-driving/streamlit_app.py", line 23, in <module>
    import os, urllib, cv2
File "/home/appuser/.local/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
x-special/nautilus-clipboard

```

I noticed the error had to do with opencv, so i decided to try the **demo-self-driving** app of streamlit to see how they handled this error, it turns out this app has the very same error, the app{demo-self-driving} works perfectly when i run:

```
streamlit run https://raw.githubusercontent.com/streamlit/demo-self-driving/master/streamlit_app.py
```

**Comment by randyzwitch** [comment]
Thanks for reporting.

Fixed by https://github.com/streamlit/demo-self-driving/pull/21

**Comment by JAGUAR1617** [comment]
facing same issue
